server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://umc-database.cgvbtostc96f.ap-northeast-2.rds.amazonaws.com/udemy-instagram?autoReconnect=true# 변경해주세요
    username: admin
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전